# Configuração da aplicação PetGet
spring:
  application:
    name: petget-backend
  
  # Configuração do banco de dados
  datasource:
    url: jdbc:postgresql://localhost:5432/petget
    username: petget
    password: petget
    driver-class-name: org.postgresql.Driver
  
  # Configuração do JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo
  
  # Configuração do Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  # Configuração do Jackson
  jackson:
    time-zone: America/Sao_Paulo
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  
  # Configuração de CORS
  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

# Configuração do servidor
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

# Configuração de logging
logging:
  level:
    com.petget: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuração do Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Configuração personalizada da aplicação
petget:
  jwt:
    secret: "petget-jwt-secret-key-change-in-production"
    expiration: 86400000 # 24 horas em millisegundos
    refresh-expiration: 604800000 # 7 dias em millisegundos
  
  # Configuração de multi-tenancy
  multitenancy:
    enabled: true
    header-name: "X-Tenant-Id"
  
  # Configuração de integrações
  integrations:
    viacep:
      base-url: "https://viacep.com.br/ws"
    asaas:
      base-url: "https://sandbox.asaas.com/api/v3"
      api-key: "change-me"
    whatsapp:
      enabled: false
      api-url: "https://graph.facebook.com/v18.0"
      access-token: "change-me"

---
# Perfil de desenvolvimento
spring:
  config:
    activate:
      on-profile: dev
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.petget: DEBUG

---
# Perfil de produção
spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    com.petget: INFO
  file:
    name: logs/petget.log